const member = [
  {
    id: 249,
    image: "https://jkt48.com/profile/amanda_sukma.jpg?v=20230530",
    name: "Amanda Sukma",
    memberStatus: "Reguler",
  },
  {
    id: 204,
    image: "https://jkt48.com/profile/angelina_christy.jpg?v=20230116",
    name: "Angelina Christy",
    memberStatus: "Reguler",
  },
  {
    id: 250,
    image: "https://jkt48.com/profile/aurellia.jpg?v=20230531",
    name: "Aurellia",
    memberStatus: "Reguler",
  },
  {
    id: 200,
    image: "https://jkt48.com/profile/azizi_asadel.jpg?v=20230116",
    name: "Azizi Asadel",
    memberStatus: "Reguler",
  },
  {
    id: 251,
    image: "https://jkt48.com/profile/callista_alifia.jpg?v=20230531",
    name: "Callista Alifia",
    memberStatus: "Reguler",
  },
  {
    id: 221,
    image: "https://jkt48.com/profile/cornelia_vanisa.jpg?v=20230116",
    name: "Cornelia Vanisa",
    memberStatus: "Reguler",
  },
  {
    id: 213,
    image: "https://jkt48.com/profile/febriola_sinambela.jpg?v=20230116",
    name: "Febriola Sinambela",
    memberStatus: "Reguler",
  },
  {
    id: 76,
    image: "https://jkt48.com/profile/feni_fitriyanti.jpg?v=20230116",
    name: "Feni Fitriyanti",
    memberStatus: "Reguler",
  },
  {
    id: 223,
    image: "https://jkt48.com/profile/fiony_alveria.jpg?v=20230116",
    name: "Fiony Alveria",
    memberStatus: "Reguler",
  },
  {
    id: 234,
    image: "https://jkt48.com/profile/flora_shafiq.jpg?v=20230116",
    name: "Flora Shafiq",
    memberStatus: "Reguler",
  },
  {
    id: 214,
    image: "https://jkt48.com/profile/freya_jayawardana.jpg?v=20230116",
    name: "Freya Jayawardana",
    memberStatus: "Reguler",
  },
  {
    id: 252,
    image: "https://jkt48.com/profile/gabriela_abigail.jpg?v=20230531",
    name: "Gabriela Abigail",
    memberStatus: "Reguler",
  },
  {
    id: 190,
    image: "https://jkt48.com/profile/gita_sekar_andarini.jpg?v=20230116",
    name: "Gita Sekar Andarini",
    memberStatus: "Reguler",
  },
  {
    id: 270,
    image: "https://jkt48.com/profile/grace_octaviani.jpg?v=20231212",
    name: "Grace Octaviani",
    memberStatus: "Reguler",
  },
  {
    id: 271,
    image: "https://jkt48.com/profile/greesella_adhalia.jpg?v=20231212",
    name: "Greesella Adhalia",
    memberStatus: "Reguler",
  },
  {
    id: 210,
    image: "https://jkt48.com/profile/helisma_putri.jpg?v=20230116",
    name: "Helisma Putri",
    memberStatus: "Reguler",
  },
  {
    id: 241,
    image: "https://jkt48.com/profile/indah_cahya.jpg?v=20230116",
    name: "Indah Cahya",
    memberStatus: "Reguler",
  },
  {
    id: 253,
    image: "https://jkt48.com/profile/indira_seruni.jpg?v=20230531",
    name: "Indira Seruni",
    memberStatus: "Reguler",
  },
  {
    id: 215,
    image: "https://jkt48.com/profile/jessica_chandra.jpg?v=20230116",
    name: "Jessica Chandra",
    memberStatus: "Reguler",
  },
  {
    id: 254,
    image: "https://jkt48.com/profile/jesslyn_elly.jpg?v=20230531",
    name: "Jesslyn Elly",
    memberStatus: "Reguler",
  },
  {
    id: 242,
    image: "https://jkt48.com/profile/kathrina_irene.jpg?v=20230116",
    name: "Kathrina Irene",
    memberStatus: "Reguler",
  },
  {
    id: 228,
    image: "https://jkt48.com/profile/lulu_salsabila.jpg?v=20230116",
    name: "Lulu Salsabila",
    memberStatus: "Reguler",
  },
  {
    id: 243,
    image: "https://jkt48.com/profile/marsha_lenathea.jpg?v=20230116",
    name: "Marsha Lenathea",
    memberStatus: "Reguler",
  },
  {
    id: 199,
    image: "https://jkt48.com/profile/mutiara_azzahra.jpg?v=20230116",
    name: "Mutiara Azzahra",
    memberStatus: "Reguler",
  },
  {
    id: 255,
    image: "https://jkt48.com/profile/raisha_syifa.jpg?v=20230530",
    name: "Raisha Syifa",
    memberStatus: "Reguler",
  },
  {
    id: 232,
    image: "https://jkt48.com/profile/reva_fidela.jpg?v=20230116",
    name: "Reva Fidela",
    memberStatus: "Reguler",
  },
  {
    id: 112,
    image: "https://jkt48.com/profile/shani_indira_natio.jpg?v=20230116",
    name: "Shani Indira Natio",
    memberStatus: "Reguler",
  },
  {
    id: 113,
    image: "https://jkt48.com/profile/shania_gracia.jpg?v=20230116",
    name: "Shania Gracia",
    memberStatus: "Reguler",
  },
  {
    id: 277,
    image: "https://jkt48.com/profile/abigail_rachel.jpg",
    name: "Abigail Rachel",
    memberStatus: "Trainee",
  },
  {
    id: 278,
    image: "https://jkt48.com/profile/adeline_wijaya.jpg",
    name: "Adeline Wijaya",
    memberStatus: "Trainee",
  },
  {
    id: 279,
    image: "https://jkt48.com/profile/aisa_maharani.jpg",
    name: "Aisa Maharani",
    memberStatus: "Trainee",
  },
  {
    id: 260,
    image: "https://jkt48.com/profile/alya_amanda.jpg?v=20231212",
    name: "Alya Amanda",
    memberStatus: "Reguler",
  },
  {
    id: 262,
    image: "https://jkt48.com/profile/anindya_ramadhani.jpg?v=20231212",
    name: "Anindya Ramadhani",
    memberStatus: "Reguler",
  },
  {
    id: 280,
    image: "https://jkt48.com/profile/aurhel_alana.jpg?v=20231212",
    name: "Aurhel Alana",
    memberStatus: "Reguler",
  },
  {
    id: 281,
    image: "https://jkt48.com/profile/catherina_vallencia.jpg",
    name: "Catherina Vallencia",
    memberStatus: "Trainee",
  },
  {
    id: 263,
    image: "https://jkt48.com/profile/cathleen_nixie.jpg?v=20231212",
    name: "Cathleen Nixie",
    memberStatus: "Reguler",
  },
  {
    id: 264,
    image: "https://jkt48.com/profile/celline_thefani.jpg?v=20231212",
    name: "Celline Thefani",
    memberStatus: "Reguler",
  },
  {
    id: 265,
    image: "https://jkt48.com/profile/chelsea_davina.jpg?v=20231212",
    name: "Chelsea Davina",
    memberStatus: "Reguler",
  },
  {
    id: 266,
    image: "https://jkt48.com/profile/cynthia_yaputera.jpg?v=20231212",
    name: "Cynthia Yaputera",
    memberStatus: "Reguler",
  },
  {
    id: 267,
    image: "https://jkt48.com/profile/dena_natalia.jpg?v=20231212",
    name: "Dena Natalia",
    memberStatus: "Reguler",
  },
  {
    id: 268,
    image: "https://jkt48.com/profile/desy_natalia.jpg?v=20231212",
    name: "Desy Natalia",
    memberStatus: "Reguler",
  },
  {
    id: 282,
    image: "https://jkt48.com/profile/fritzy_rosmerian.jpg",
    name: "Fritzy Rosmerian",
    memberStatus: "Trainee",
  },
  {
    id: 269,
    image: "https://jkt48.com/profile/gendis_mayrannisa.jpg?v=20231212",
    name: "Gendis Mayrannisa",
    memberStatus: "Reguler",
  },
  {
    id: 283,
    image: "https://jkt48.com/profile/hillary_abigail.jpg",
    name: "Hillary Abigail",
    memberStatus: "Trainee",
  },
  {
    id: 284,
    image: "https://jkt48.com/profile/jazzlyn_trisha.jpg",
    name: "Jazzlyn Trisha",
    memberStatus: "Trainee",
  },
  {
    id: 272,
    image: "https://jkt48.com/profile/jeane_victoria.jpg?v=20231212",
    name: "Jeane Victoria",
    memberStatus: "Reguler",
  },
  {
    id: 285,
    image: "https://jkt48.com/profile/letycia_moreen.jpg?v=20231212",
    name: "Letycia Moreen",
    memberStatus: "Reguler",
  },
  {
    id: 273,
    image: "https://jkt48.com/profile/michelle_alexandra.jpg?v=20231212",
    name: "Michelle Alexandra",
    memberStatus: "Reguler",
  },
  {
    id: 286,
    image: "https://jkt48.com/profile/michelle_levia.jpg",
    name: "Michelle Levia",
    memberStatus: "Trainee",
  },
  {
    id: 287,
    image: "https://jkt48.com/profile/nayla_suji.jpg",
    name: "Nayla Suji",
    memberStatus: "Trainee",
  },
  {
    id: 288,
    image: "https://jkt48.com/profile/nina_tutachia.jpg?v=20231212",
    name: "Nina Tutachia",
    memberStatus: "Reguler",
  },
  {
    id: 289,
    image: "https://jkt48.com/profile/oline_manuel.jpg",
    name: "Oline Manuel",
    memberStatus: "Trainee",
  },
  {
    id: 290,
    image: "https://jkt48.com/profile/regina_wilian.jpg",
    name: "Regina Wilian",
    memberStatus: "Trainee",
  },
  {
    id: 291,
    image: "https://jkt48.com/profile/ribka_budiman.jpg",
    name: "Ribka Budiman",
    memberStatus: "Trainee",
  },
  {
    id: 292,
    image: "https://jkt48.com/profile/shabilqis_naila.jpg",
    name: "Shabilqis Naila",
    memberStatus: "Trainee",
  },
  {
    id: 293,
    image: "https://jkt48.com/profile/victoria_kimberly.jpg",
    name: "Victoria Kimberly",
    memberStatus: "Trainee",
  },
];

export default member;
