const detail = [
  {
    id: "249",
    image: "https://jkt48.com/profile/amanda_sukma.jpg?v=20230530",
    fullName: "Amanda Sukma",
    birthday: "17 Desember 2004",
    bloodType: "O",
    zodiac: "Sagitarius",
    height: "160cm",
    nickname: "Amanda",
  },
  {
    id: "204",
    image: "https://jkt48.com/profile/angelina_christy.jpg?v=20230116",
    fullName: "Angelina Christy",
    birthday: "5 Desember 2005",
    bloodType: "O",
    zodiac: "Sagitarius",
    height: "163cm",
    nickname: "Christy",
  },
  {
    id: "250",
    image: "https://jkt48.com/profile/aurellia.jpg?v=20230531",
    fullName: "Aurellia",
    birthday: "29 Oktober 2002",
    bloodType: "O",
    zodiac: "Scorpio",
    height: "155cm",
    nickname: "Lia",
  },
  {
    id: "200",
    image: "https://jkt48.com/profile/azizi_asadel.jpg?v=20230116",
    fullName: "Azizi Asadel",
    birthday: "16 Mei 2004",
    bloodType: "O",
    zodiac: "Taurus",
    height: "162cm",
    nickname: "Zee",
  },
  {
    id: "251",
    image: "https://jkt48.com/profile/callista_alifia.jpg?v=20230531",
    fullName: "Callista Alifia",
    birthday: "8 Agustus 2005",
    bloodType: "O",
    zodiac: "Leo",
    height: "157cm",
    nickname: "Callie",
  },
  {
    id: "221",
    image: "https://jkt48.com/profile/cornelia_vanisa.jpg?v=20230116",
    fullName: "Cornelia Vanisa",
    birthday: "26 Juli 2002",
    bloodType: "O",
    zodiac: "Leo",
    height: "162cm",
    nickname: "Oniel",
  },
  {
    id: "213",
    image: "https://jkt48.com/profile/febriola_sinambela.jpg?v=20230116",
    fullName: "Febriola Sinambela",
    birthday: "26 Februari 2005",
    bloodType: "B",
    zodiac: "Pisces",
    height: "154cm",
    nickname: "Olla",
  },
  {
    id: "76",
    image: "https://jkt48.com/profile/feni_fitriyanti.jpg?v=20230116",
    fullName: "Feni Fitriyanti",
    birthday: "16 Januari 1999",
    bloodType: "O",
    zodiac: "Capricorn",
    height: "162cm",
    nickname: "Feni",
  },
  {
    id: "223",
    image: "https://jkt48.com/profile/fiony_alveria.jpg?v=20230116",
    fullName: "Fiony Alveria",
    birthday: "4 Februari 2002",
    bloodType: "O",
    zodiac: "Aquarius",
    height: "158cm",
    nickname: "Fiony",
  },
  {
    id: "243",
    image: "https://jkt48.com/profile/marsha_lenathea.jpg?v=20230116",
    fullName: "Marsha Lenathea",
    birthday: "9 Januari 2006",
    bloodType: "O",
    zodiac: "Capricorn",
    height: "163cm",
    nickname: "Marsha",
  },
  {
    id: "214",
    image: "https://jkt48.com/profile/freya_jayawardana.jpg?v=20230116",
    fullName: "Freya Jayawardana",
    birthday: "13 Februari 2006",
    bloodType: "B",
    zodiac: "Aquarius",
    height: "154cm",
    nickname: "Freya",
  },
  {
    id: "252",
    image: "https://jkt48.com/profile/gabriela_abigail.jpg?v=20230531",
    fullName: "Gabriela Abigail",
    birthday: "7 Agustus 2006",
    bloodType: "B",
    zodiac: "Leo",
    height: "160cm",
    nickname: "Ella",
  },
  {
    id: "190",
    image: "https://jkt48.com/profile/gita_sekar_andarini.jpg?v=20230116",
    fullName: "Gita Sekar Andarini",
    birthday: "30 Juni 2001",
    bloodType: "O",
    zodiac: "Cancer",
    height: "165cm",
    nickname: "Gita",
  },
  {
    id: "270",
    image: "https://jkt48.com/profile/grace_octaviani.jpg?v=20231212",
    fullName: "Grace Octaviani",
    birthday: "18 Oktober 2007",
    bloodType: "B",
    zodiac: "Libra",
    height: "165cm",
    nickname: "Gracie",
  },
  {
    id: "234",
    image: "https://jkt48.com/profile/flora_shafiq.jpg?v=20230116",
    fullName: "Flora Shafiq",
    birthday: "4 April 2005",
    bloodType: "B",
    zodiac: "Aries",
    height: "149cm",
    nickname: "Flora",
  },
  {
    id: "271",
    image: "https://jkt48.com/profile/greesella_adhalia.jpg?v=20231212",
    fullName: "Greesella Adhalia",
    birthday: "10 Januari 2006",
    bloodType: "O",
    zodiac: "Capricorn",
    height: "165cm",
    nickname: "Greesel",
  },
  {
    id: "210",
    image: "https://jkt48.com/profile/helisma_putri.jpg?v=20230116",
    fullName: "Helisma Putri",
    birthday: "15 Juni 2000",
    bloodType: "A",
    zodiac: "Gemini",
    height: "165cm",
    nickname: "Eli",
  },
  {
    id: "241",
    image: "https://jkt48.com/profile/indah_cahya.jpg?v=20230116",
    fullName: "Indah Cahya",
    birthday: "20 Maret 2001",
    bloodType: "A",
    zodiac: "Pisces",
    height: "165cm",
    nickname: "Indah",
  },
  {
    id: "253",
    image: "https://jkt48.com/profile/indira_seruni.jpg?v=20230531",
    fullName: "Indira Seruni",
    birthday: "26 April 2004",
    bloodType: "A",
    zodiac: "Taurus",
    height: "160cm",
    nickname: "Indira",
  },
  {
    id: "215",
    image: "https://jkt48.com/profile/jessica_chandra.jpg?v=20230116",
    fullName: "Jessica Chandra",
    birthday: "23 September 2005",
    bloodType: "O",
    zodiac: "Libra",
    height: "163cm",
    nickname: "Jessi",
  },
  {
    id: "254",
    image: "https://jkt48.com/profile/jesslyn_elly.jpg?v=20230531",
    fullName: "Jesslyn Elly",
    birthday: "13 September 2001",
    bloodType: "O",
    zodiac: "Virgo",
    height: "155cm",
    nickname: "Lyn",
  },
  {
    id: "242",
    image: "https://jkt48.com/profile/kathrina_irene.jpg?v=20230116",
    fullName: "Kathrina Irene",
    birthday: "26 Juli 2006",
    bloodType: "A",
    zodiac: "Leo",
    height: "165cm",
    nickname: "Kathrina",
  },
  {
    id: "228",
    image: "https://jkt48.com/profile/lulu_salsabila.jpg?v=20230116",
    fullName: "Lulu Salsabila",
    birthday: "23 Oktober 2002",
    bloodType: "B",
    zodiac: "Scorpio",
    height: "157cm",
    nickname: "Lulu",
  },
  {
    id: "199",
    image: "https://jkt48.com/profile/mutiara_azzahra.jpg?v=20230116",
    fullName: "Mutiara Azzahra",
    birthday: "12 Juli 2004",
    bloodType: "B",
    zodiac: "Cancer",
    height: "158cm",
    nickname: "Muthe",
  },
  {
    id: "255",
    image: "https://jkt48.com/profile/raisha_syifa.jpg?v=20230530",
    fullName: "Raisha Syifa",
    birthday: "11 November 2007",
    bloodType: "AB",
    zodiac: "Scorpio",
    height: "163cm",
    nickname: "Raisha",
  },
  {
    id: "232",
    image: "https://jkt48.com/profile/reva_fidela.jpg?v=20230116",
    fullName: "Reva Fidela",
    birthday: "14 Juli 2006",
    bloodType: "A",
    zodiac: "Cancer",
    height: "159cm",
    nickname: "Adel",
  },
  {
    id: "112",
    image: "https://jkt48.com/profile/shani_indira_natio.jpg?v=20230116",
    fullName: "Shani Indira Natio",
    birthday: "5 Oktober 1998",
    bloodType: "B",
    zodiac: "Libra",
    height: "167cm",
    nickname: "Shani",
  },
  {
    id: "113",
    image: "https://jkt48.com/profile/shania_gracia.jpg?v=20230116",
    fullName: "Shania Gracia",
    birthday: "31 Agustus 1999",
    bloodType: "A",
    zodiac: "Virgo",
    height: "161cm",
    nickname: "Gracia",
  },
  {
    id: "277",
    image: "https://jkt48.com/profile/abigail_rachel.jpg",
    fullName: "Abigail Rachel",
    birthday: "6 Agustus 2008",
    bloodType: "B",
    zodiac: "Leo",
    height: "161cm",
    nickname: "Aralie",
  },
  {
    id: "278",
    image: "https://jkt48.com/profile/adeline_wijaya.jpg",
    fullName: "Adeline Wijaya",
    birthday: "1 September 2007",
    bloodType: "B",
    zodiac: "Virgo",
    height: "167cm",
    nickname: "Delynn",
  },
  {
    id: "279",
    image: "https://jkt48.com/profile/aisa_maharani.jpg",
    fullName: "Aisa Maharani",
    birthday: "31 Januari 2006",
    bloodType: "B",
    zodiac: "Aquarius",
    height: "162cm",
    nickname: "Shasa",
  },
  {
    id: "260",
    image: "https://jkt48.com/profile/alya_amanda.jpg?v=20231212",
    fullName: "Alya Amanda",
    birthday: "26 Agustus 2006",
    bloodType: "A",
    zodiac: "Virgo",
    height: "165cm",
    nickname: "Alya",
  },
  {
    id: "262",
    image: "https://jkt48.com/profile/anindya_ramadhani.jpg?v=20231212",
    fullName: "Anindya Ramadhani",
    birthday: "18 Oktober 2005",
    bloodType: "O",
    zodiac: "Libra",
    height: "154cm",
    nickname: "Anindya",
  },
  {
    id: "280",
    image: "https://jkt48.com/profile/aurhel_alana.jpg?v=20231212",
    fullName: "Aurhel Alana",
    birthday: "14 September 2006",
    bloodType: "-",
    zodiac: "Virgo",
    height: "163cm",
    nickname: "Lana",
  },
  {
    id: "281",
    image: "https://jkt48.com/profile/catherina_vallencia.jpg",
    fullName: "Catherina Vallencia",
    birthday: "21 Agustus 2007",
    bloodType: "B",
    zodiac: "Leo",
    height: "163cm",
    nickname: "Erine",
  },
  {
    id: "263",
    image: "https://jkt48.com/profile/cathleen_nixie.jpg?v=20231212",
    fullName: "Cathleen Nixie",
    birthday: "28 Mei 2009",
    bloodType: "A",
    zodiac: "Gemini",
    height: "158cm",
    nickname: "Cathy",
  },
  {
    id: "264",
    image: "https://jkt48.com/profile/celline_thefani.jpg?v=20231212",
    fullName: "Celline Thefani",
    birthday: "9 April 2007",
    bloodType: "O",
    zodiac: "Aries",
    height: "163cm",
    nickname: "Elin",
  },
  {
    id: "265",
    image: "https://jkt48.com/profile/chelsea_davina.jpg?v=20231212",
    fullName: "Chelsea Davina",
    birthday: "23 Desember 2009",
    bloodType: "B",
    zodiac: "Capricorn",
    height: "168cm",
    nickname: "Chelsea",
  },
  {
    id: "266",
    image: "https://jkt48.com/profile/cynthia_yaputera.jpg?v=20231212",
    fullName: "Cynthia Yaputera",
    birthday: "22 November 2003",
    bloodType: "O",
    zodiac: "Sagitarius",
    height: "158cm",
    nickname: "Cynthia",
  },
  {
    id: "267",
    image: "https://jkt48.com/profile/dena_natalia.jpg?v=20231212",
    fullName: "Dena Natalia",
    birthday: "16 Desember 2005",
    bloodType: "O",
    zodiac: "Sagitarius",
    height: "162cm",
    nickname: "Danella",
  },
  {
    id: "268",
    image: "https://jkt48.com/profile/desy_natalia.jpg?v=20231212",
    fullName: "Desy Natalia",
    birthday: "16 Desember 2005",
    bloodType: "O",
    zodiac: "Sagitarius",
    height: "165cm",
    nickname: "Daisy",
  },
  {
    id: "282",
    image: "https://jkt48.com/profile/fritzy_rosmerian.jpg",
    fullName: "Fritzy Rosmerian",
    birthday: "28 Juli 2008",
    bloodType: "A",
    zodiac: "Leo",
    height: "157cm",
    nickname: "Fritzy",
  },
  {
    id: "269",
    image: "https://jkt48.com/profile/gendis_mayrannisa.jpg?v=20231212",
    fullName: "Gendis Mayrannisa",
    birthday: "23 Juni 2010",
    bloodType: "B",
    zodiac: "Cancer",
    height: "160cm",
    nickname: "Gendis",
  },
  {
    id: "283",
    image: "https://jkt48.com/profile/hillary_abigail.jpg",
    fullName: "Hillary Abigail",
    birthday: "19 Oktober 2007",
    bloodType: "O",
    zodiac: "Libra",
    height: "160cm",
    nickname: "Lily",
  },
  {
    id: "284",
    image: "https://jkt48.com/profile/jazzlyn_trisha.jpg",
    fullName: "Jazzlyn Trisha",
    birthday: "16 Februari 2011",
    bloodType: "O",
    zodiac: "Aquarius",
    height: "164cm",
    nickname: "Trisha",
  },
  {
    id: "272",
    image: "https://jkt48.com/profile/jeane_victoria.jpg?v=20231212",
    fullName: "Jeane Victoria",
    birthday: "5 Juni 2006",
    bloodType: "O",
    zodiac: "Gemini",
    height: "164cm",
    nickname: "Jeane",
  },
  {
    id: "285",
    image: "https://jkt48.com/profile/letycia_moreen.jpg?v=20231212",
    fullName: "Letycia Moreen",
    birthday: "7 Juni 2010",
    bloodType: "O",
    zodiac: "Gemini",
    height: "160cm",
    nickname: "Moreen",
  },
  {
    id: "273",
    image: "https://jkt48.com/profile/michelle_alexandra.jpg?v=20231212",
    fullName: "Michelle Alexandra",
    birthday: "22 April 2009",
    bloodType: "O",
    zodiac: "Taurus",
    height: "160cm",
    nickname: "Michie",
  },
  {
    id: "286",
    image: "https://jkt48.com/profile/michelle_levia.jpg",
    fullName: "Michelle Levia",
    birthday: "24 Januari 2009",
    bloodType: "O",
    zodiac: "Aquarius",
    height: "168cm",
    nickname: "Levi",
  },
  {
    id: "287",
    image: "https://jkt48.com/profile/nayla_suji.jpg",
    fullName: "Nayla Suji",
    birthday: "18 Juni 2007",
    bloodType: "AB",
    zodiac: "Gemini",
    height: "161cm",
    nickname: "Nayla",
  },
  {
    id: "288",
    image: "https://jkt48.com/profile/nina_tutachia.jpg?v=20231212",
    fullName: "Nina Tutachia",
    birthday: "16 Oktober 2009",
    bloodType: "O",
    zodiac: "Libra",
    height: "162cm",
    nickname: "Nachia",
  },
  {
    id: "289",
    image: "https://jkt48.com/profile/oline_manuel.jpg",
    fullName: "Oline Manuel",
    birthday: "3 November 2007",
    bloodType: "B",
    zodiac: "Scorpio",
    height: "167cm",
    nickname: "Oline",
  },
  {
    id: "290",
    image: "https://jkt48.com/profile/regina_wilian.jpg",
    fullName: "Regina Wilian",
    birthday: "10 Desember 2009",
    bloodType: "B",
    zodiac: "Sagitarius",
    height: "169cm",
    nickname: "Regie",
  },
  {
    id: "291",
    image: "https://jkt48.com/profile/ribka_budiman.jpg",
    fullName: "Ribka Budiman",
    birthday: "13 Januari 2009",
    bloodType: "O",
    zodiac: "Capricorn",
    height: "163cm",
    nickname: "Ribka",
  },
  {
    id: "292",
    image: "https://jkt48.com/profile/shabilqis_naila.jpg",
    fullName: "Shabilqis Naila",
    birthday: "1 September 2008",
    bloodType: "B",
    zodiac: "Virgo",
    height: "160cm",
    nickname: "Nala",
  },
  {
    id: "293",
    image: "https://jkt48.com/profile/victoria_kimberly.jpg",
    fullName: "Victoria Kimberly",
    birthday: "8 Maret 2010",
    bloodType: "AB",
    zodiac: "Pisces",
    height: "158cm",
    nickname: "Kimmy",
  },
];

export default detail;
